// @ts-check
/**
 * Prepares publication without deleting declarations used by local incremental builds or the
 * docs editor. npm reads the generated dist/.npmignore when packing the package's dist folder.
 * JavaScript comment stripping and embedded CSS compaction are explicit, package-specific flags.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { pathToFileURL } from "node:url";
import { transformSync } from "esbuild";
import ts from "typescript";
import { stripComments } from "./strip-dist-comments.mjs";

const ignoreHeader = "# Generated by scripts/prepare-package.mjs; regenerated before every pack.";
const declarationPattern = /\.d\.[cm]?ts$/u;

/** @param {string} directory @returns {string[]} */
function filesUnder(directory) {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const file = join(directory, entry.name);
    return entry.isDirectory() ? filesUnder(file) : [file];
  });
}

/** @param {unknown} exports @returns {string[]} */
function declarationExports(exports) {
  if (typeof exports === "string") {
    if (!declarationPattern.test(exports)) return [];
    if (exports.includes("*")) throw new Error("Expand declaration export patterns before packing");
    return [exports];
  }
  if (exports !== null && typeof exports === "object") {
    return Object.values(exports).flatMap(declarationExports);
  }
  return [];
}

/**
 * Follows re-exports, import types, and triple-slash references from every public type entry.
 * An unresolved local edge fails packing instead of silently excluding a required declaration.
 * @param {string} packageRoot
 * @returns {string[]} Package-relative declarations that npm should exclude.
 */
export function unusedDeclarations(packageRoot) {
  packageRoot = resolve(packageRoot);
  const dist = join(packageRoot, "dist");
  const manifest = JSON.parse(readFileSync(join(packageRoot, "package.json"), "utf8"));
  const roots = declarationExports(manifest.exports);
  if (roots.length === 0) throw new Error("Package must declare its public type exports");
  /** @type {Set<string>} */
  const reachable = new Set();
  /** @type {ts.CompilerOptions} */
  const options = { moduleResolution: ts.ModuleResolutionKind.Bundler, resolveJsonModule: true };
  const cache = ts.createModuleResolutionCache(packageRoot, (file) => file, options);

  /** @param {string} file */
  function visit(file) {
    file = resolve(file);
    if (!file.startsWith(dist + sep) || reachable.has(file)) return;
    if (!existsSync(file)) throw new Error(`Missing public declaration dependency: ${file}`);
    reachable.add(file);
    if (!declarationPattern.test(file)) return;
    const info = ts.preProcessFile(readFileSync(file, "utf8"), true, true);
    for (const imported of info.importedFiles) {
      const target = ts.resolveModuleName(
        imported.fileName,
        file,
        options,
        ts.sys,
        cache,
      ).resolvedModule;
      if (target?.resolvedFileName !== undefined) visit(target.resolvedFileName);
      else if (imported.fileName.startsWith(".")) {
        throw new Error(`Unresolved declaration import ${imported.fileName} in ${file}`);
      }
    }
    for (const reference of info.referencedFiles) visit(resolve(dirname(file), reference.fileName));
    for (const reference of info.typeReferenceDirectives) {
      const target = ts.resolveTypeReferenceDirective(
        reference.fileName,
        file,
        options,
        ts.sys,
      ).resolvedTypeReferenceDirective;
      if (target?.resolvedFileName !== undefined) visit(target.resolvedFileName);
      else if (reference.fileName.startsWith(".")) {
        throw new Error(`Unresolved declaration reference ${reference.fileName} in ${file}`);
      }
    }
  }

  for (const entry of roots) {
    const file = resolve(packageRoot, entry);
    if (!file.startsWith(dist + sep)) throw new Error(`Public types must be inside dist: ${entry}`);
    visit(file);
  }
  return filesUnder(dist)
    .filter((file) => declarationPattern.test(file) && !reachable.has(file))
    .map((file) => relative(packageRoot, file).split(sep).join("/"))
    .sort();
}

/**
 * Only whitespace is minified: selectors, declarations, identifiers, and browser syntax stay
 * intact. Parse the JS literal instead of importing a module during npm's publication hook.
 * @param {string} source
 */
export function compactEmbeddedStyles(source) {
  const file = ts.createSourceFile("styles.js", source, ts.ScriptTarget.Latest, true);
  for (const statement of file.statements) {
    if (!ts.isVariableStatement(statement)) continue;
    for (const declaration of statement.declarationList.declarations) {
      const literal = declaration.initializer;
      if (!ts.isIdentifier(declaration.name) || declaration.name.text !== "styles") continue;
      if (
        literal === undefined ||
        !(ts.isStringLiteral(literal) || ts.isNoSubstitutionTemplateLiteral(literal))
      ) {
        throw new Error("Embedded styles must be a static string literal");
      }
      const css = transformSync(literal.text, { loader: "css", minifyWhitespace: true });
      if (css.warnings.length !== 0) throw new Error("Embedded CSS produced parser warnings");
      return (
        source.slice(0, literal.getStart(file)) +
        JSON.stringify(css.code) +
        source.slice(literal.end)
      );
    }
  }
  throw new Error("Cannot find the embedded styles export");
}

/**
 * @param {string} packageRoot
 * @param {{ stripJavaScriptComments?: boolean, compactStyles?: boolean }} [options]
 */
export function preparePackage(packageRoot, options = {}) {
  const dist = join(packageRoot, "dist");
  const ignored = unusedDeclarations(packageRoot);
  const ignoreFile = join(dist, ".npmignore");
  if (existsSync(ignoreFile) && !readFileSync(ignoreFile, "utf8").startsWith(ignoreHeader + "\n")) {
    throw new Error(`Refusing to replace an unrecognized ${ignoreFile}`);
  }
  if (options.stripJavaScriptComments === true) {
    for (const file of filesUnder(dist).filter((file) => file.endsWith(".js"))) {
      const source = readFileSync(file, "utf8");
      const stripped = stripComments(source);
      if (stripped !== source) writeFileSync(file, stripped);
    }
  }
  if (options.compactStyles === true) {
    const file = join(dist, "styles.js");
    const source = readFileSync(file, "utf8");
    const compacted = compactEmbeddedStyles(source);
    if (compacted !== source) writeFileSync(file, compacted);
  }
  writeFileSync(
    ignoreFile,
    [ignoreHeader, ...ignored.map((file) => "/" + file.slice("dist/".length)), ""].join("\n"),
  );
  return ignored;
}

if (
  process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(resolve(process.argv[1])).href
) {
  const flags = process.argv.slice(2);
  if (flags.some((flag) => !["--strip-comments", "--compact-css"].includes(flag))) {
    throw new Error("Usage: prepare-package.mjs [--strip-comments] [--compact-css]");
  }
  const ignored = preparePackage(process.cwd(), {
    stripJavaScriptComments: flags.includes("--strip-comments"),
    compactStyles: flags.includes("--compact-css"),
  });
  console.error(`prepare-package: excluded ${String(ignored.length)} internal declarations`);
}
