/**
 * Writes one compatibility fixture: a database built by *this* build, frozen on disk.
 *
 * A browser database's data lives in the user's browser, not on a server, so it outlives every
 * deploy. Once a format ships, the reader therefore has to keep accepting what that build wrote.
 * The moment an old version reader disappears, every database using it becomes unreadable, and
 * nothing would report it.
 *
 * These fixtures are what reports it. Each one is a snapshot — which carries the raw block bytes
 * verbatim, so it pins the block format and the snapshot envelope together — plus a manifest of
 * queries and the answers this build gives for them. `format-compatibility.test.ts` opens every
 * fixture on every run and checks the answers still hold.
 *
 * Run this when either format version changes, *before* changing it:
 *
 *     npm run fixture:format
 *
 * The output is named for the versions it was written at, so fixtures accumulate rather than
 * replace one another. Never delete a released, locked fixture: it is the only remaining copy of
 * what that release wrote, and once the code that produced it is gone it cannot be regenerated.
 * Before the first lock, an explicitly unsupported experimental fixture may be replaced; block 2
 * is Minnow's first locked format.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { SNAPSHOT_FORMAT_VERSION } from "../packages/core/src/storage/snapshot.js";
import { BLOCK_FORMAT_VERSION } from "../packages/core/src/block-format/index.js";
import { createFormatFixtureArtifact } from "../packages/core/src/storage/fixture-shape.js";

const directory = new URL("../packages/core/format-fixtures/", import.meta.url);
mkdirSync(fileURLToPath(directory), { recursive: true });

// The shared generator freezes the database clock and IDs, records the query answers, and exports
// the framed bytes. The compatibility test calls this same function and byte-compares the result.
const { bytes, expectations } = await createFormatFixtureArtifact();
const stem = `block${String(BLOCK_FORMAT_VERSION)}-snapshot${String(SNAPSHOT_FORMAT_VERSION)}`;

writeFileSync(new URL(`${stem}.minnow`, directory), bytes);
writeFileSync(
  new URL(`${stem}.json`, directory),
  `${JSON.stringify(
    {
      blockFormatVersion: BLOCK_FORMAT_VERSION,
      snapshotFormatVersion: SNAPSHOT_FORMAT_VERSION,
      // Deliberately not a timestamp: the file has to be byte-stable across regenerations, or
      // every run shows up as a diff and nobody reads them.
      note: "Generated by npm run fixture:format. Never edit or delete; see the script header.",
      expectations,
    },
    null,
    2,
  )}\n`,
);

console.log(`Wrote format-fixtures/${stem}.minnow (${String(bytes.byteLength)} bytes)`);
console.log(`Wrote format-fixtures/${stem}.json (${String(expectations.length)} expectations)`);
